FROM {{ item.image }}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y procps python3-apt-dbg python3-apt python-apt-doc python-apt-common wget python sudo bash ca-certificates && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install procps wget python3.11 sudo python3.11-devel python3-dnf bash && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache && yum install -y procps wget python3.11 sudo bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache wget python3 sudo bash ca-certificates; fi
