{
 "title": "Jenkins / Node / Jobs",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jenkins_cluster",
    "query": {
     "query": "query_result(default_jenkins_up)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(default_jenkins_builds_last_build_duration_milliseconds{instance=\"$jenkins_cluster\"},jenkins_job)"
    }
   },
   {
    "name": "build_number",
    "query": {
     "query": "label_values(default_jenkins_builds_build_result{jenkins_job=\"$job\"},number)"
    }
   },
   {
    "name": "build_status",
    "query": {
     "query": "label_values(default_jenkins_builds_build_result{instance=\"$jenkins_cluster\", jenkins_job=\"$job\", number=\"$build_number\"},status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job start time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_build_start_time_milliseconds{instance=\"$jenkins_cluster\", jenkins_job=\"$job\", number=\"$build_number\"}",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Job duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_build_duration_milliseconds{instance=\"$jenkins_cluster\", jenkins_job=\"$job\", number=\"$build_number\"}",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Build status",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "options": { "content": "# ${build_status}" },
   "targets": [
    {
     "expr": "default_jenkins_builds_build_result{instance=\"$jenkins_cluster\", jenkins_job=\"$job\", number=\"$build_number\"}"
    }
   ]
  },
  {
   "title": "Job avg duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(default_jenkins_builds_build_duration_milliseconds{instance=\"$jenkins_cluster\", jenkins_job=\"$job\"})",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Jenkins builds health score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "default_jenkins_builds_health_score{jenkins_job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last build stage duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_stage_duration_milliseconds_summary_sum{instance=\"$jenkins_cluster\", jenkins_job=\"$job\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  }
 ]
}