---
- name: Converge
  hosts: all
  gather_facts: true
  collections:
    - devops.devops_monitoring_collection
  roles:
    - role: ansible_role_pve_exporter
      vars:
        pve_exporter_is_install: false
        pve_exporter_config:
          user: root@pam
          password: "root123"
          verify_ssl: false
