---
proxmox_is_enterprise: false
pve_exporter_is_install: true
prometheus_pve_exporter_version: 3.2.2

prometheus_pve_exporter_user: prometheus
prometheus_pve_exporter_group: prometheus

prometheus_pve_exporter_root_dir: /opt/prometheus-pve-exporter
prometheus_pve_exporter_config_dir: /etc/prometheus

pve_exporter_config:
  user: root@pam
  password: "root123"
  verify_ssl: false
