---
- name: Ensure grafana configuration directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: grafana
  with_items:
    - "/etc/grafana"
    - "/etc/grafana/provisioning"
    - "/etc/grafana/provisioning/datasources"
    - "/etc/grafana/provisioning/dashboards"
    - "/etc/grafana/provisioning/notifiers"
    - "/etc/grafana/provisioning/plugins"

- name: Create grafana main configuration file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0640
  notify:
    - Start or restart Grafana with service
    - Start or restart Grafana with sysvinit
    - Waiting for the service to start

- name: Create grafana LDAP configuration file
  ansible.builtin.template:
    src: ldap.toml.j2
    dest: "{{ grafana_auth.ldap.config_file | default('/etc/grafana/ldap.toml') }}"
    owner: root
    group: grafana
    mode: 0640
  when:
    - "'ldap' in grafana_auth"
    - "'enabled' not in grafana_auth.ldap or grafana_auth.ldap.enabled"
  notify:
    - Start or restart Grafana with service
    - Start or restart Grafana with sysvinit
    - Waiting for the service to start

- name: Create grafana directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "grafana"
    group: "grafana"
  with_items:
    - "{{ grafana_logs_dir }}"
    - "{{ grafana_data_dir }}"
    - "{{ grafana_data_dir }}/dashboards"
    - "{{ grafana_data_dir }}/plugins"

- block:
    - name: Create grafana socket directory
      ansible.builtin.file:
        path: "{{ grafana_server.socket | dirname }}"
        state: directory
        mode: 0775
        owner: "grafana"
        group: "grafana"

    - name: Ensure grafana socket directory created on startup
      ansible.builtin.template:
        src: tmpfiles.j2
        dest: /etc/tmpfiles.d/grafana.conf
        owner: root
        group: root
        mode: 0644
  when:
    - grafana_server.protocol is defined and grafana_server.protocol == 'socket'
    - grafana_server.socket | dirname != '/var/run'
  notify:
    - Start or restart Grafana with service
    - Start or restart Grafana with sysvinit
    - Waiting for the service to start

- meta: flush_handlers
