---
- name: Import select organization file
  ansible.builtin.include_tasks: select_organization.yml

- name: Update notification policies
  ansible.builtin.uri:
    url: "{{ grafana_api_url }}/api/v1/provisioning/policies"
    user: "{{ grafana_security.admin_user }}"
    password: "{{ grafana_security.admin_password }}"
    force_basic_auth: true
    method: PUT
    body_format: json
    body: "{{ item | to_json }}"
    status_code:
      - 202
