---
prometheus_is_install: true
prometheus_version: 2.47.2
prometheus_release_name: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_gomaxprocs: "{{ ansible_processor_vcpus|default(ansible_processor_count) }}"

prometheus_user: prometheus
prometheus_group: prometheus

prometheus_root_dir: /opt/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_log_dir: /var/log/prometheus
prometheus_db_dir: /var/lib/prometheus
prometheus_dist_dir: "{{ prometheus_root_dir }}/dist"
prometheus_bin_dir: "{{ prometheus_root_dir }}/current"
prometheus_rules_dir: "{{ prometheus_config_dir }}/rules"
prometheus_file_sd_config_dir: "{{ prometheus_config_dir }}/tgroups"

prometheus_rules_src_dir: "{{ playbook_dir }}/files/prometheus/alerts"
prometheus_config_src_dir: "{{ playbook_dir }}/templates/prometheus/config"

prometheus_rules_files: []

prometheus_web_listen_address: ":9090"
prometheus_web_external_url: 'http://localhost:9090/'

prometheus_config_flags:
  'config.file': '{{ prometheus_config_dir }}/prometheus.yml'
  'storage.tsdb.path': '{{ prometheus_db_dir }}'
  'web.listen-address': '{{ prometheus_web_listen_address }}'
  'web.external-url': '{{ prometheus_web_external_url }}'
  'web.console.templates': '/etc/prometheus/consoles'
  'web.console.libraries': '/etc/prometheus/console_libraries'

prometheus_config_flags_extra: {}
prometheus_pam_domain: "prometheus"
prometheus_pam_nofile_value: "1024"

alert_file:
  - name: alert.rules
