---
- name: Delete proxmox list files if do not enterprise
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/sources.list.d/ceph.list
    - /etc/apt/sources.list.d/pve-enterprise.list
  when: proxmox_is_enterprise is false

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install needed packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-is-python3
    - python3-minimal
    - python3-apt
    - python3-pip
    - python3-venv
    - virtualenv

- name: Create prometheus system group
  ansible.builtin.group:
    name: "{{ prometheus_pve_exporter_group }}"
    system: yes
    state: present

- name: Create prometheus system user
  ansible.builtin.user:
    name: "{{ prometheus_pve_exporter_user }}"
    system: yes
    shell: "/sbin/nologin"
    group: "{{ prometheus_pve_exporter_group }}"
    groups: "ssl-cert"
    createhome: no

- name: Create prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_pve_exporter_user }}"
    group: "{{ prometheus_pve_exporter_group }}"
    mode: 0755
  with_items:
    - "{{ prometheus_pve_exporter_root_dir }}"
    - "{{ prometheus_pve_exporter_config_dir }}"

- name: Create virtual env
  ansible.builtin.pip:
    name: "prometheus-pve-exporter=={{ prometheus_pve_exporter_version }}"
    virtualenv: /opt/prometheus-pve-exporter
