---
- name: Converge
  hosts: all
  gather_facts: true
  collections:
    - devops.devops_monitoring_collection
  roles:
    - role: ansible_role_prometheus
      vars:
        prometheus_is_install: false
        prometheus_config_flags:
          'config.file': '{{ prometheus_config_dir }}/prometheus.yml'
          'storage.tsdb.path': '{{ prometheus_db_dir }}'
          'web.listen-address': '{{ prometheus_web_listen_address }}'
          'web.external-url': '{{ prometheus_web_external_url }}'
          'web.console.templates': '/etc/prometheus/consoles'
          'web.console.libraries': '/etc/prometheus/console_libraries'
