---
galaxy_info:
  role_name: ansible_role_prometheus
  author: Laszlo Beres
  description: Deploy Prometheus Service
  license: "GPL-2.0-or-later"
  min_ansible_version: '7.6.0'
  dependencies: []
  galaxy_tags:
    - monitoring
  platforms:
    - name: Ubuntu
      versions:
        - focal
